name: Deploy WebSite

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Site
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            git clone git@github.com:sistematico/php-mvc-lite.git /var/www/labs.lucasbrum.net/projetos/php-mvc-lite
            cd /var/www/labs.lucasbrum.net/projetos/php-mvc-lite
            git pull
            